### ISSUE TITLE
[Bug] Proxima data catalog issues for github/package-security

### ISSUE THREAD

**Issue by stankovski** [github/actions-oidc-gateway-example#7]
## Summary

Thank you for filling out the data catalog spreadsheet as part of the https://github.com/github/fanout/issues/1850! Unfortunately, not all required columns in the spreadsheet were populated. At your earliest convenience, please go over the below issues and update the data in the original spreadsheet.

Shared drive: [data](https://drive.google.com/drive/folders/1oDlXc9calVQyYtCqBDITSRP6LQ6yyjys)
Spreadsheet name: github/package-security
Original authors: @phillmv, @trevrosen
 
## Details

The following data quality issues were found in the Proxima data catalog spreadsheet for service `github/package-security`:
 - [ ] Hydro Data Missing: 1 data elements (there are data elements in the `Hydro` sheet that are neither marked as "N/A" nor have the "Classification - Category" column populated)
        
### Source

https://github.com/github/proxima/issues/3732

### 📅 Key Dates

Due by: 8/31/2024

### Team Assigned

@github/actions-oidc-gateway-example

**Comment by phillmv** [comment]
In the Hydro worksheet, under the  "Classification - category" column? Where? https://docs.google.com/spreadsheets/d/1rj-ZEzkNMtARX2W03h7a_uVTMynmyU8TW8Fy3qoW5-I/edit?gid=931201616#gid=931201616 Which one? I don't see it.

**Comment by phillmv** [comment]
I bugged @stankovski and I was given the go-ahead to close this issue.
